theme: jekyll-theme-minimal
title: Max Janssens - SpaceTimeGlobe
description: Bestanden voor leerkrachten mbt het maken en gebruiken van de 3D geprinte spacetime globe
show_downloads: true
markdown: kramdown
